version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/work
    steps:
      - checkout
      - run: yarn
      - run:
          name: type check
          command: yarn type-check
